config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	resources :users, except: :create
	post 'create_user' => 'users#create', as: :create_user  

	resources :atendimentos do
		collection do
			get 'search'
		end
	end

	root 'atendimentos#index'

end

app/models/atendimento.rb
class Atendimento < ActiveRecord::Base

	validates :title, presence: {message: "Você precisa preencher esse campo."}
	validates :date, presence: {message: "Você precisa preencher esse campo."}, uniqueness: {message: "Já tem atendimento cadastrado para esse dia/horário, tente outro."}
	
	def self.search(query)
		where("LOWER(title) like ?", "%#{query}%") 
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	validates :email, uniqueness: true
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable


	def user_admin
		if admin == true
			user_admin = 'Sim'
			else
			user_admin = 'Não'
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	#before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:fullname, :email, :password, :password_confirmation, :remember_me, :admin) }
		devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:fullname, :email, :password, :password_confirmation, :current_password, :admin) }
	end  

end

app/controllers/atendimentos_controller.rb
class AtendimentosController < ApplicationController
	before_action :set_atendimento, only: [:show, :edit, :update, :destroy]

	# GET /atendimentos
	# GET /atendimentos.json
	def search
		if params[:search]
			@atendimentos = Atendimento.search(params[:search]).order("date ASC")
		else
			@atendimentos = Atendimento.all.order('date ASC').limit(100)
		end
	end

	def index
		if current_user.present?
			@atendimentos = Atendimento.all
		else
			redirect_to '/users/sign_in'
		end
	end

	# GET /atendimentos/1
	# GET /atendimentos/1.json
	def show
	end

	# GET /atendimentos/new
	def new
		@atendimento = Atendimento.new
	end

	# GET /atendimentos/1/edit
	def edit
	end

	# POST /atendimentos
	# POST /atendimentos.json
	def create
		@atendimento = Atendimento.new(atendimento_params)

		respond_to do |format|
			if @atendimento.save
				flash[:success] = 'Agendamento cadastrado com sucesso!'
				format.html { redirect_to @atendimento }
				format.json { render :show, status: :created, location: @atendimento }
			else
				format.html { render :new }
				format.json { render json: @atendimento.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /atendimentos/1
	# PATCH/PUT /atendimentos/1.json
	def update
		respond_to do |format|
			if @atendimento.update(atendimento_params)
				flash[:success] = 'Agendamento alterado com sucesso!'
				format.html { redirect_to @atendimento }
				format.json { render :show, status: :ok, location: @atendimento }
			else
				format.html { render :edit }
				format.json { render json: @atendimento.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /atendimentos/1
	# DELETE /atendimentos/1.json
	def destroy
		@atendimento.destroy
		respond_to do |format|
			flash[:success] = 'Agendamento deletado com sucesso!'
			format.html { redirect_to atendimentos_url }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_atendimento
		@atendimento = Atendimento.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def atendimento_params
		params.require(:atendimento).permit(:date, :title, :description)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authorize_admin, only: :create

	def index
		@users = User.all.order('fullname ASC')
	end

	# GET /atendimentos/1
	# GET /atendimentos/1.json
	def show
	end

	# GET /atendimentos/new
	def new
		@user = User.new
	end

	# GET /atendimentos/1/edit
	def edit

	end


	def create
		@user = User.new(user_params)
		respond_to do |format|
			if @user.save
				flash[:success] = 'Usuário cadastrado com sucesso!'
				format.html { redirect_to users_url }
				format.json { render :show, status: :created, location: @user }
			else
				format.html { render :new }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
	# PATCH/PUT /users/1
	# PATCH/PUT /users/1.json
	def update
		respond_to do |format|
			if @user.update(user_params)
				flash[:success] = 'Usuário alterado com sucesso!'
				format.html { redirect_to users_url }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		@user = User.find(params[:id])
		if @user.present?
			@user.destroy
			respond_to do |format|
				flash[:success] = 'Usuário deletado com sucesso!'
				format.html { redirect_to users_url }
				format.json { head :no_content }
			end
		end

	end

	private

	# This should probably be abstracted to ApplicationController
	# as shown by diego.greyrobot
	def authorize_admin
		return unless !current_user.admin?
		redirect_to root_path, alert: 'Apenas Administradores!'
	end
	def set_user
		@user = User.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def user_params
		params.require(:user).permit(:fullname, :email, :password, :password_confirmation, :remember_me, :admin)
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/atendimentos/_form.html.erb
<%= form_for(@atendimento) do |f| %>
<% if @atendimento.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@atendimento.errors.count, "error") %> prohibited this atendimento from being saved:</h2>

	<ul>
		<% @atendimento.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

	<div class="row">
		<div class="form-group col-lg-4">
			<%= f.label 'Data:', class: 'control-label' %><br>
			<%= f.text_field( :date, id: 'datetimepicker', class: 'form-control') %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-lg-6">
			<%= f.label 'Cliente:' %><br>

			<%= f.text_field :title, :class => "form-control" %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-lg-8">
			<%= f.label 'Observações:' %><br>
			<%= f.text_area :description, :class => "form-control" %>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-6"></div>
		<div class="actions">
			<%= f.submit 'Salvar', :class => 'btn btn-primary' %>
			<%= link_to 'Voltar', atendimentos_path, :class => 'btn btn-default' %>
		</div>
	</div>
</div>

<% end %>
<script>
	$(document).ready(function(){
		jQuery('#datetimepicker').datetimepicker({
			format:'d/m/Y H:i',
			lang: 'pt-BR',
			allowTimes:[
				'8:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '21:00', '21:30'
			],
			step:1
		});

	})

</script>

app/views/atendimentos/edit.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-9"><h1>Editar Atendimento</h1>

<%= render 'form' %>
</div>

app/views/atendimentos/index.html.erb
<%= link_to 'Novo Atendimento', new_atendimento_path, :class => 'btn btn-primary pull-right' %>
<br><br><br>
<div id="calendar"></div>
<script>



	var calendar = $('#calendar').fullCalendar({
		lang: 'pt-br',
		defaultTimedEventDuration: '00:30:00',
		header: {
			left: 'prev,next today',
			center: 'title',
			right: 'month,agendaWeek,agendaDay'
		},
		events: '/atendimentos.json'
		// put your options and callbacks here

	})
</script>


<br>

app/views/atendimentos/new.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-9">
	<h1>Novo Atendimento</h1>

	<%= render 'form' %>

	
</div>

app/views/atendimentos/search.html.erb
<div class="page-header" style="text-align: center">
	<h1>Atendimentos</h1>
</div>

<br />
<div class="container-fluid">
	<div class="row">
		<label class="pull-right" style="margin-right: 2%"><%= Atendimento.count %> atendimentos cadastrados</label> 
	</div>
	<%= link_to 'Novo Atendimento', new_atendimento_path, class: "btn btn-primary pull-right" %>

	<%= form_tag(search_atendimentos_path, :method => "get", :class => "form-inline pull-right", id: "search-form", style: "margin-right: 2%") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Buscar Atendimento", class: "form-control" %>
	<%= button_tag " ", :title => nil, class: "btn btn-default glyphicon glyphicon-search" %>
	<% end %>
	<br />
	<br />
	<br />
	<table class="table">
		<thead>
			<tr>
				<th>Código</th>
				<th>Data</th>
				<th>Cliente</th>
				<th>Observações</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @atendimentos.each do |atendimento| %>
			<tr>
				<td><%= atendimento.id %></td>
				<td><%= atendimento.date.strftime("%-d/%-m/%Y %H:%M") %></td>
				<td><%= atendimento.title %></td>
				<td><%= atendimento.description %></td>
				<td><%= link_to 'Ver', atendimento, class: "btn btn-primary btn-xs" %></td>
				<td><%= link_to 'Editar', edit_atendimento_path(atendimento), class: "btn btn-warning btn-xs" %></td>
				<td><%= link_to 'Deletar', atendimento, method: :delete, data: { confirm: 'Você tem certeza que deseja excluir?' }, class: "btn btn-danger btn-xs" %></td>
			</tr>
			<% end %>
		</div>
	</tbody>
</table>

app/views/atendimentos/show.html.erb
<center>
<br><br><br><br>
	<label>Atendimento nº:</label>
	<%= @atendimento.id %>
	<br><br>
	<label>Data:</label>
	<%= @atendimento.date.strftime("%-d/%-m/%Y %H:%M") %>
	<br><br>



	<label>Cliente:</label>
	<%= @atendimento.title %>
	<br><br>


	<label>Observações:</label>
	<%= @atendimento.description %>
	<br><br>

	<%= link_to 'Editar', edit_atendimento_path(@atendimento), :class => 'btn btn-primary' %> |
	<%= link_to 'Voltar', atendimentos_path, :class => 'btn btn-default' %>
</center>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Agenda</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a class="navbar-brand" href="http://localhost:3000">Brand</a>
				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
					</ul>

					<ul class="nav navbar-nav navbar-right"><% if current_user.present? %>
						<li>
							<a>Olá, <%= current_user.fullname %></a>
						</li>
						<li><%= link_to '',search_atendimentos_path, class: "glyphicon glyphicon-search" %></li>
						<li><%= link_to 'Atendimentos', atendimentos_path %></li>

						<% if current_user.present? %><li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Usuários <span class="caret"></span></a>

						<ul class="dropdown-menu" role="menu">
							<% if current_user.admin %>
							<li><%= link_to 'Cadastrar', new_user_path %></li>
							<li class="divider"></li>
							<li><%= link_to 'Ver Todos/Excluir', users_path %></li>
							<% end %>
							<li class="divider"></li>
							<li><%= link_to 'Editar', edit_user_registration_path %></li>
						</ul>
						</li>
						<% end %>


						<li>
							<%= link_to('Sair', destroy_user_session_path, :method => :delete) %>
							<%# else %>
</li>
	<li>
	<%#= link_to "Entrar", new_user_session_path %>
<% end %>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<br><br><br>
		<div class="container">
			<%= render 'layouts/messages' %>

			<%= yield %>

		</div>
		<br><br><br><br><br>
	</body>
</html>

app/views/users/_form.html.erb
<%= form_for User.new, url: create_user_path do |f| %>
<div class="form-group">
	<%= f.label 'Nome:' %><br />
	<%= f.text_field :fullname, autofocus: true, :class => "form-control" %>
</div>

<div class="form-group">
	<%= f.label 'E-mail:' %><br />
	<%= f.email_field :email, :class => "form-control" %>
</div>

<div class="form-group">
	<%= f.label 'Senha:' %>
	<% if @validatable %>
	<em>(<%= @minimum_password_length %> caracteres minímos)</em>
	<% end %><br />
	<%= f.password_field :password, autocomplete: "off", :class => "form-control" %>
</div>

<div class="form-group">
	<%= f.label 'Confirmar senha:' %><br />
	<%= f.password_field :password_confirmation, autocomplete: "off", :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label 'Administrador' %>&ensp;
	<%= f.check_box :admin, {:checked=>false}, "true", "false" %>
</div>

<div class="actions">
	<%= link_to 'Voltar', users_path, :class => 'btn btn-default pull-right' %><%= f.submit "Salvar", class: 'btn btn-primary pull-right', style: 'margin-right: 10px' %>
	
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="col-lg-4"></div>
<div class="col-lg-4">
	<h1>Editar Usuários</h1>
	<%= form_for @user, url: edit_user_path  do |f| %>
	<div class="form-group">
		<%= f.label 'Nome:' %><br />
		<%= f.text_field :fullname, autofocus: true, :class => "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label 'E-mail:' %><br />
		<%= f.email_field :email, :class => "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label 'Senha:' %>
		<% if @validatable %>
		<em>(<%= @minimum_password_length %> caracteres minímos)</em>
		<% end %><br />
		<%= f.password_field :password, autocomplete: "off", :class => "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label 'Confirmar senha:' %><br />
		<%= f.password_field :password_confirmation, autocomplete: "off", :class => "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label 'Administrador' %>&ensp;
		<%= f.check_box :admin,  "true", "false" %>
	</div>

	<div class="actions">
		<%= link_to 'Voltar', users_path, :class => 'btn btn-default pull-right' %><%= f.submit "Salvar", class: 'btn btn-primary pull-right', style: 'margin-right: 10px' %>
		<% end %>

	</div>

app/views/users/index.html.erb
<div class="page-header" style="text-align: center">
	<h1>Usuários</h1>
</div>

<br />
<div class="container-fluid">


	<%= link_to 'Novo Usuário', new_user_path, class: "btn btn-primary", style: "float: right" %>

	<table class="table">
		<%= %>
		<thead>
			<tr>
				<th>Código</th>
				<th>Nome</th>
				<th>E-mail</th>
				<th>Admin</th>
				<th>Último acesso</th>
				<th colspan="1"></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= user.id %></td>
				<td><%= user.fullname %></td>
				<td><%= user.email %></td>
				<td><%= user.user_admin %></td>
				<td><% if user.last_sign_in_at != nil %><%= user.last_sign_in_at.strftime("%-d/%-m/%Y %H:%M") %><% end %></td>
				<!--<td><%= link_to 'Ver', user, class: "btn btn-primary btn-xs" %></td>-->
				<!--<td><%= link_to 'Editar', edit_user_path(user), class: "btn btn-warning btn-xs" %></td>-->

				<td><% if current_user.id != user.id && user.email != 'admin@admin.com.br' %><%= link_to 'Deletar', user, method: :delete, data: { confirm: 'Você tem certeza que deseja excluir?' }, class: "btn btn-danger btn-xs" %>
					<% else %>
					<% end %>
				</td>
			</tr>

			<% end %>
		</div>

	</tbody>
</table>


<br>

app/views/users/new.html.erb
<div class="col-lg-4"></div>
<div class="col-lg-4">
	<h1>Novo Usuário</h1>
	<%= render 'form' %>
</div>